- name: Ensure UFW is installed
  apt:
    package: ufw
    state: present

- name: Ensure UFW is enabled and running
  service:
    name: ufw
    state: started
    enabled: yes

- name: Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify:
    - restart ufw

# Allow SSH on port 22 explicitly
- name: Allow SSH on port 22
  ansible.builtin.ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Allow specified ports on UFW
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ open_ports }}"

- name: Deny all other inbound traffic (optional)
  ufw:
    rule: deny
    direction: in

- name: Enable UFW
  ufw: state=enabled
